# Generated by Django 3.2 on 2021-05-19 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='cgpa',
            field=models.FloatField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='dep',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='sem',
            field=models.IntegerField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.IntegerField(max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='address',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='email',
            field=models.EmailField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_id',
            field=models.IntegerField(max_length=200, null=True, unique=True),
        ),
    ]
