# Generated by Django 3.2 on 2021-05-20 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210520_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='sem',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
